(cl:in-package dynamixel_workbench_msgs-msg)
(cl:export '(MODEL_NUMBER-VAL
          MODEL_NUMBER
          VERSION_OF_FIRMWARE-VAL
          VERSION_OF_FIRMWARE
          ID-VAL
          ID
          BAUD_RATE-VAL
          BAUD_RATE
          RETURN_DELAY_TIME-VAL
          RETURN_DELAY_TIME
          CW_ANGLE_LIMIT-VAL
          CW_ANGLE_LIMIT
          CCW_ANGLE_LIMIT-VAL
          CCW_ANGLE_LIMIT
          DRIVE_MODE-VAL
          DRIVE_MODE
          THE_HIGHEST_LIMIT_TEMPERATURE-VAL
          THE_HIGHEST_LIMIT_TEMPERATURE
          THE_LOWEST_LIMIT_VOLTAGE-VAL
          THE_LOWEST_LIMIT_VOLTAGE
          THE_HIGHEST_LIMIT_VOLTAGE-VAL
          THE_HIGHEST_LIMIT_VOLTAGE
          MAX_TORQUE-VAL
          MAX_TORQUE
          STATUS_RETURN_LEVEL-VAL
          STATUS_RETURN_LEVEL
          ALARM_LED-VAL
          ALARM_LED
          ALARM_SHUTDOWN-VAL
          ALARM_SHUTDOWN
          MULTI_TURN_OFFSET-VAL
          MULTI_TURN_OFFSET
          RESOLUTION_DIVIDER-VAL
          RESOLUTION_DIVIDER
          TORQUE_ENABLE-VAL
          TORQUE_ENABLE
          LED-VAL
          LED
          D_GAIN-VAL
          D_GAIN
          I_GAIN-VAL
          I_GAIN
          P_GAIN-VAL
          P_GAIN
          GOAL_POSITION-VAL
          GOAL_POSITION
          MOVING_SPEED-VAL
          MOVING_SPEED
          TORQUE_LIMIT-VAL
          TORQUE_LIMIT
          PRESENT_POSITION-VAL
          PRESENT_POSITION
          PRESENT_SPEED-VAL
          PRESENT_SPEED
          PRESENT_LOAD-VAL
          PRESENT_LOAD
          PRESENT_VOLTAGE-VAL
          PRESENT_VOLTAGE
          PRESENT_TEMPERATURE-VAL
          PRESENT_TEMPERATURE
          REGISTERED-VAL
          REGISTERED
          MOVING-VAL
          MOVING
          LOCK-VAL
          LOCK
          PUNCH-VAL
          PUNCH
          CURRENT-VAL
          CURRENT
          TORQUE_CONTROL_MODE_ENABLE-VAL
          TORQUE_CONTROL_MODE_ENABLE
          GOAL_TORQUE-VAL
          GOAL_TORQUE
          GOAL_ACCELERATION-VAL
          GOAL_ACCELERATION
))