// Generated by gencpp from file behaviour_msgs/GameControllerPlayerMsg.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERPLAYERMSG_H
#define BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERPLAYERMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour_msgs
{
template <class ContainerAllocator>
struct GameControllerPlayerMsg_
{
  typedef GameControllerPlayerMsg_<ContainerAllocator> Type;

  GameControllerPlayerMsg_()
    : penalty(0)
    , secsTillUnpenalised(0)  {
    }
  GameControllerPlayerMsg_(const ContainerAllocator& _alloc)
    : penalty(0)
    , secsTillUnpenalised(0)  {
  (void)_alloc;
    }



   typedef uint8_t _penalty_type;
  _penalty_type penalty;

   typedef uint8_t _secsTillUnpenalised_type;
  _secsTillUnpenalised_type secsTillUnpenalised;





  typedef boost::shared_ptr< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> const> ConstPtr;

}; // struct GameControllerPlayerMsg_

typedef ::behaviour_msgs::GameControllerPlayerMsg_<std::allocator<void> > GameControllerPlayerMsg;

typedef boost::shared_ptr< ::behaviour_msgs::GameControllerPlayerMsg > GameControllerPlayerMsgPtr;
typedef boost::shared_ptr< ::behaviour_msgs::GameControllerPlayerMsg const> GameControllerPlayerMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator1> & lhs, const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator2> & rhs)
{
  return lhs.penalty == rhs.penalty &&
    lhs.secsTillUnpenalised == rhs.secsTillUnpenalised;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator1> & lhs, const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc3d426fa7888f90b568c965b79d41d6";
  }

  static const char* value(const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc3d426fa7888f90ULL;
  static const uint64_t static_value2 = 0xb568c965b79d41d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/GameControllerPlayerMsg";
  }

  static const char* value(const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 penalty\n"
"uint8 secsTillUnpenalised\n"
;
  }

  static const char* value(const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.penalty);
      stream.next(m.secsTillUnpenalised);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GameControllerPlayerMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::GameControllerPlayerMsg_<ContainerAllocator>& v)
  {
    s << indent << "penalty: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.penalty);
    s << indent << "secsTillUnpenalised: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.secsTillUnpenalised);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERPLAYERMSG_H
