(cl:in-package behaviour_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VERSION-VAL
          VERSION
          PACKETNUMBER-VAL
          PACKETNUMBER
          PLAYERSPERTEAM-VAL
          PLAYERSPERTEAM
          GAMEPHASE-VAL
          GAMEPHASE
          STATE-VAL
          STATE
          SETPLAY-VAL
          SETPLAY
          FIRSTHALF-VAL
          FIRSTHALF
          KICKINGTEAM-VAL
          KICKINGTEAM
          DROPINTEAM-VAL
          DROPINTEAM
          DROPINTIME-VAL
          DROPINTIME
          SECSREMAINING-VAL
          SECSREMAINING
          SECONDARYTIME-VAL
          SECONDARYTIME
          TEAMS-VAL
          TEAMS
))