# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from behaviour_msgs/ActionMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ActionMsg(genpy.Message):
  _md5sum = "2f6660362f84530fb73c09c0b8fc889f"
  _type = "behaviour_msgs/ActionMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
bool ball_tracking
bool center_ball
bool align_body
bool walk
bool kick
int32 defend
bool squat
bool goal_tracking
"""
  __slots__ = ['ball_tracking','center_ball','align_body','walk','kick','defend','squat','goal_tracking']
  _slot_types = ['bool','bool','bool','bool','bool','int32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ball_tracking,center_ball,align_body,walk,kick,defend,squat,goal_tracking

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActionMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ball_tracking is None:
        self.ball_tracking = False
      if self.center_ball is None:
        self.center_ball = False
      if self.align_body is None:
        self.align_body = False
      if self.walk is None:
        self.walk = False
      if self.kick is None:
        self.kick = False
      if self.defend is None:
        self.defend = 0
      if self.squat is None:
        self.squat = False
      if self.goal_tracking is None:
        self.goal_tracking = False
    else:
      self.ball_tracking = False
      self.center_ball = False
      self.align_body = False
      self.walk = False
      self.kick = False
      self.defend = 0
      self.squat = False
      self.goal_tracking = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5Bi2B().pack(_x.ball_tracking, _x.center_ball, _x.align_body, _x.walk, _x.kick, _x.defend, _x.squat, _x.goal_tracking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.ball_tracking, _x.center_ball, _x.align_body, _x.walk, _x.kick, _x.defend, _x.squat, _x.goal_tracking,) = _get_struct_5Bi2B().unpack(str[start:end])
      self.ball_tracking = bool(self.ball_tracking)
      self.center_ball = bool(self.center_ball)
      self.align_body = bool(self.align_body)
      self.walk = bool(self.walk)
      self.kick = bool(self.kick)
      self.squat = bool(self.squat)
      self.goal_tracking = bool(self.goal_tracking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5Bi2B().pack(_x.ball_tracking, _x.center_ball, _x.align_body, _x.walk, _x.kick, _x.defend, _x.squat, _x.goal_tracking))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.ball_tracking, _x.center_ball, _x.align_body, _x.walk, _x.kick, _x.defend, _x.squat, _x.goal_tracking,) = _get_struct_5Bi2B().unpack(str[start:end])
      self.ball_tracking = bool(self.ball_tracking)
      self.center_ball = bool(self.center_ball)
      self.align_body = bool(self.align_body)
      self.walk = bool(self.walk)
      self.kick = bool(self.kick)
      self.squat = bool(self.squat)
      self.goal_tracking = bool(self.goal_tracking)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5Bi2B = None
def _get_struct_5Bi2B():
    global _struct_5Bi2B
    if _struct_5Bi2B is None:
        _struct_5Bi2B = struct.Struct("<5Bi2B")
    return _struct_5Bi2B
