# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from behaviour_msgs/GameControllerTeamMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import behaviour_msgs.msg

class GameControllerTeamMsg(genpy.Message):
  _md5sum = "eb0242679c00f249e2e638f89df925ef"
  _type = "behaviour_msgs/GameControllerTeamMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 teamNumber
uint8 teamColour
GameControllerPlayerMsg[] players
================================================================================
MSG: behaviour_msgs/GameControllerPlayerMsg
uint8 penalty
uint8 secsTillUnpenalised"""
  __slots__ = ['teamNumber','teamColour','players']
  _slot_types = ['uint8','uint8','behaviour_msgs/GameControllerPlayerMsg[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       teamNumber,teamColour,players

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GameControllerTeamMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.teamNumber is None:
        self.teamNumber = 0
      if self.teamColour is None:
        self.teamColour = 0
      if self.players is None:
        self.players = []
    else:
      self.teamNumber = 0
      self.teamColour = 0
      self.players = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.teamNumber, _x.teamColour))
      length = len(self.players)
      buff.write(_struct_I.pack(length))
      for val1 in self.players:
        _x = val1
        buff.write(_get_struct_2B().pack(_x.penalty, _x.secsTillUnpenalised))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.players is None:
        self.players = None
      end = 0
      _x = self
      start = end
      end += 2
      (_x.teamNumber, _x.teamColour,) = _get_struct_2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.players = []
      for i in range(0, length):
        val1 = behaviour_msgs.msg.GameControllerPlayerMsg()
        _x = val1
        start = end
        end += 2
        (_x.penalty, _x.secsTillUnpenalised,) = _get_struct_2B().unpack(str[start:end])
        self.players.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.teamNumber, _x.teamColour))
      length = len(self.players)
      buff.write(_struct_I.pack(length))
      for val1 in self.players:
        _x = val1
        buff.write(_get_struct_2B().pack(_x.penalty, _x.secsTillUnpenalised))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.players is None:
        self.players = None
      end = 0
      _x = self
      start = end
      end += 2
      (_x.teamNumber, _x.teamColour,) = _get_struct_2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.players = []
      for i in range(0, length):
        val1 = behaviour_msgs.msg.GameControllerPlayerMsg()
        _x = val1
        start = end
        end += 2
        (_x.penalty, _x.secsTillUnpenalised,) = _get_struct_2B().unpack(str[start:end])
        self.players.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
